### PR TITLE
Added a new feature - Latest VAC bans

### PR DESCRIPTION
**Pull request by jsifuentes**
I thought this may be an interesting feature to have. It's a list just like Latest Tracked Users that allows you to see recently tracked VAC bans. On my local copy of VacStatus, all works well. 

I'd like your thoughts on it @jung3o. Do you think this would be an interesting feature to have?

### CODE REVIEW

**Comment by jung3o** [comment]
this is a fun one. Yeah I'm perfectly okay with this feature :)
Btw, you want to edit the jsx under resources isntead of the file in public.

It's a bad idea from me that i kept the files in public, but they're not for editing.
https://github.com/jung3o/VacStatus/blob/master/resources/assets/jsx/pages/listPortal.jsx

damn you must've had some struggle with looking through my code. Thanks a lot for helping out!

**Comment by jung3o** [comment]
Thanks, is this ready for production?

**Comment by jsifuentes** [comment]
Heh, going through and figuring everything out was a trial and error job. :)

I think this should be ready to go. Works locally here.

**Comment by jung3o** [comment]
hmm looks like something went wrong. https://vacstat.us/list/latest/vac
I gtg but ill be back soon to check out what's wrong

**Comment by jsifuentes** [comment]
I'll take a look on my local copy and make a hotfix pull request soon.

**Comment by jung3o** [comment]
@jsifuentes haha everyone loves your latest vac page
google analytics

**Comment by jsifuentes** [comment]
Haha, thats awesome!

**Pull request merged**
